openapi: 3.0.3
info:
  title: Mock Security API
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8000
paths:
  /users/{userId}/profile:
    get:
      summary: Get user profile
      parameters:
        - name: userId
          in: path
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
        '401': { description: Unauthenticated }
        '404': { description: Not Found }
