openapi: 3.0.3
info:
  title: Mock Security API
  version: 1.1.0
servers:
  - url: http://127.0.0.1:8000

paths:
  /users/{userId}/profile:
    get:
      summary: Get user profile
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200': { description: OK }
        '401': { description: Unauthenticated }
        '404': { description: Not Found }

    patch:
      summary: Update user profile (self-only)
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string }
                name: { type: string }
      responses:
        '200': { description: Updated }
        '401': { description: Unauthenticated }
        '403': { description: Forbidden }     # cross-tenant edit is blocked in the app
        '404': { description: Not Found }

  /accounts/{accountId}/transfer:
    post:
      summary: Transfer between accounts
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [toAccountId, amount]
              properties:
                toAccountId: { type: string }
                amount:
                  type: number
      responses:
        '200': { description: Transfer processed }   # app returns 200 (even for unauth/x-tenant by design)
        '400': { description: Bad Request }
        '401': { description: Unauthenticated }
        '404': { description: Not Found }

  /orders/{orderId}/cancel:
    delete:
      summary: Cancel an order
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200': { description: Cancelled }       # app returns 200 for all three paths in current mock
        '401': { description: Unauthenticated }
        '403': { description: Forbidden }
        '404': { description: Not Found }

  /admin/reports:
    get:
      summary: Admin-only report
      responses:
        '200': { description: OK }              # allowed for token t1 per app.py
        '401': { description: Unauthenticated }
        '403': { description: Forbidden }
